# Definition for CI within GitLab
# Note:
#    Prefix any job name with a '.' to disable.
#


# Enable submodules
variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive


# Default caching paths, between jobs
cache:
  paths:
    - .env


#### Static Analysis Jobs ####
lint:
  stage: static
  script:
    - bash ci/run lint
  artifacts:
    when: always
    paths:
      - artifacts
    reports:
      junit:
        - artifacts/lint-results.xml

.docs:
  stage: static
  script:
    - bash ci/run docs
  artifacts:
    when: always
    paths:
      - artifacts
    reports:
      junit: artifacts/docs-results.xml


#### Build Jobs ####
build:
  stage: build
  script:
    - ./do-build.sh
  artifacts:
    when: always
    paths:
      - artifacts
      - output
      - logs
    reports:
      junit: artifacts/build-results.xml
  when: always


#### Unit Test Jobs (or general test) ####
.test:
  stage: unittest
  script:
    - bash ci/run test
  dependencies: []
  artifacts:
    when: always
    paths:
      - artifacts
    reports:
      junit:
        - artifacts/test-results.xml

.test-python3:
  stage: unittest
  script:
    - bash ci/run test -3
  dependencies: []
  artifacts:
    when: always
    paths:
      - artifacts
    reports:
      junit:
        - artifacts/test-results.xml

.coverage:
  stage: unittest
  script:
    - bash ci/run coverage
  coverage: '/^Overall Coverage: (\d+(?:\.\d+)?)%.*$/'
  dependencies: []
  artifacts:
    when: always
    paths:
      - artifacts


#### Integration Test Jobs ####
.inttest:
  stage: inttest
  script:
    - bash ci/run inttest
  dependencies: []
  artifacts:
    when: always
    paths:
      - artifacts
    reports:
      junit:
        - artifacts/test-results.xml
  when: always

.inttest-python3:
  stage: inttest
  script:
    - bash ci/run inttest -3
  dependencies: []
  artifacts:
    when: always
    paths:
      - artifacts
    reports:
      junit:
        - artifacts/test-results.xml
  when: always


#### Stages to execute ####
stages:
  - static
  - build
#  - unittest
#  - inttest
