# Definition for CI within GitLab
# Note:
#    Prefix any job name with a '.' to disable.
#


# Enable submodules
variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive


# Default caching paths, between jobs
cache:
  paths:
    - .env


#### Static Analysis Jobs ####
.lint:
  stage: static
  script:
    - ./build.sh lint
  artifacts:
    when: always
    paths:
      - artifacts
    reports:
      junit:
        - artifacts/lint-results.xml


#### Build Jobs ####
build:
  stage: build
  script:
    - mkdir logs artifacts

    # PrinceXML (http://www.princexml.com/) requires a license to be used.
    # If the documents produced contain no advertising, and are provided for
    # no cost to anyone, and are published on a site that has no cost and has
    # no advertising, and providing that a link is provided to the PrinceXML
    # site, the non-commercial license can be used (even on a server).
    # Consult https://www.princexml.com/purchase/license_faq/ for more details.
    #
    # These criteria are met by the builds we're creating here, and so we can
    # use the non-commercial license.
    - PRINCEXML_I_HAVE_A_LICENSE=1 ./build.sh
    - mv output artifacts/docs

  artifacts:
    when: always
    paths:
      - artifacts
      - logs
  when: always


#### Stages to execute ####
stages:
  - static
  - build
